#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SimpleTasks.Resource", IsApplication=true)]

namespace SimpleTasks
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int new_task_button = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int new_task_button_ripple = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int text_view_ripple = 2130968578;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int checkbox = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_launcher = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int new_task_button = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int text_view_ripple = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060005
			public const int addTaskButton = 2131099653;
			
			// aapt resource value: 0x7f060002
			public const int newTaskMenuButton = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int noTaskTitle = 2131099648;
			
			// aapt resource value: 0x7f060008
			public const int taskCompleteCheckbox = 2131099656;
			
			// aapt resource value: 0x7f060001
			public const int taskListLayout = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int taskLong = 2131099652;
			
			// aapt resource value: 0x7f060007
			public const int taskLongView = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int taskSummaryText = 2131099657;
			
			// aapt resource value: 0x7f060003
			public const int taskTitle = 2131099651;
			
			// aapt resource value: 0x7f060006
			public const int taskTitleView = 2131099654;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int MainActivity = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int NewTaskActivity = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int TaskActivity = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int TaskFragment = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int ApplicationName = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int NoTaskText = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int TaskAddButton = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int TaskInputTitle = 2131034113;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
